### ISSUE TITLE
SMTP Path tag si empty in framework config       version 2.015 fresh install of server and client

### ISSUE THREAD

**Issue by JimCamp** [Luxoft/Twister#50] opened 2013-07-18 20:59 UTC
The warning is not clear but this is not a critical issue

**Comment by bogdanpopescu** [comment] 2013-07-19 04:57
@JimCamp  This is a warning message that the user doesn't have the SMTP server defined. It is design intent.
The spelling error is a duplicate of issue #47. It was fixed in the delivery on 18th July.

**Closed as completed** 2013-07-30 21:12 UTC
Labels: invalid
