### ISSUE TITLE
Server Root Configuration - Twister Installation

### ISSUE THREAD

**Issue by twistUser1** [Luxoft/Twister#136] opened 2014-07-11 05:23 UTC
Hi,
In Twister User Guide, it was asked to install Apache and configure the Server Root to /var/www

I added a line in the beginning of file -> /etc/apache2/apache2.conf : 
ServerRoot "/var/www"

But when i start the apache2 i get some error :- 

pinv@ubuntu-pinvsrs01:/home/user/twister/bin$ sudo /etc/init.d/apache2 restart
apache2: Syntax error on line 214 of /etc/apache2/apache2.conf: Include directory '/var/www/mods-enabled' not found
Action 'configtest' failed.
The Apache error log may have more information.
   ...fail!

If I comment the "ServerRoot" line added as explained above.... I did not get this error while starting apache2, but opening "http://localhost/twister" does not work...

Can any one guide me...

Thx

**Comment by bogdanpopescu** [comment] 2014-07-11 05:32
@twistUser1 
ServerRoot should remain /etc/apache2.
http://www.linuxquestions.org/questions/linux-networking-3/apache-error-folder-not-found-4175459823/
Documentation issue. It was intended to mention document root, not server root.

**Comment by bogdanpopescu** [comment] 2014-07-11 07:09
@twistUser1 
We updated the user guide to correct documentation issue.
Please close the issue.

**Closed as completed** 2014-07-14 07:15 UTC
Labels: Documentation
