### ISSUE TITLE
TscTestBedLib.py, error in line no 49

### ISSUE THREAD

**Issue by baluthomas** [Luxoft/Twister#101] opened 2013-10-18 10:09 UTC
Line 49: from **init** import PROXY

This should be from ce_libs import PROXY right?

**Comment by bogdanpopescu** [comment] 2013-10-21 06:25
@baluthomas 
This is  a duplicate of https://github.com/Luxoft/Twister/issues/100. 
Closing.

**Closed as completed by bogdanpopescu** 2013-10-21 06:25 UTC
Labels: duplicate
